services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dfoto
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  auth:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    depends_on:
      - auth-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL_HOST: auth-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./misc/dtek-realm.json:/opt/keycloak/data/import/dtek-realm.json

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - auth_db_data:/var/lib/postgresql/data
volumes:
  db_data:
  auth_db_data:
